# Enabling H2 Console
spring:
  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
#        input:
        input-city-data:
          destination: city-details
          content-type: application/*+avro
          group: group-1
#          consumer:
#            concurrency: 3
        output:
          destination: city-details
          content-type: application/*+avro
      kafka:
        binder:
          brokers: localhost:9092 # brokers do kakfa, separados por virgula
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
          consumer-properties:
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
            specific.avro.reader: true
